version: '3.2'
services:
  nginx-cactus:
    image: nginx:latest
    container_name: nginx-cactus
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./srv/:/var/www/html/"
    external_links:
      - mariadb-cactus
      - php-fpm-cactus
  mariadb-cactus:
    image: mariadb:latest
    container_name: mariadb-cactus
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SQL_ROOT_PASSWORD_TO_EDIT
    volumes:
      - "mariadb_vol:/var/lib/mysql"
  php-fpm-cactus:
    build: ./php-fpm/
    container_name: php-fpm-cactus
    restart: always
    volumes:
      - "./srv/:/var/www/html/"
    external_links:
      - mariadb-cactus
volumes:
  mariadb_vol:
